/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.quanlybanhangonl.ui;
    
import javax.swing.ImageIcon;
import javax.swing.JFrame;

    
/**
 *
 * @author Lennovo
 */
public class MainForm extends javax.swing.JFrame {
    
    private QuanLyLaptop mlaptop;
    private QuanLyMobile mMobile;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        
       /* LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);   */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jToolBar1 = new javax.swing.JToolBar();
        btn_logout = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_laptop = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_mobile = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btn_gioithieu = new javax.swing.JButton();
        tpl_mainBoard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        txt_logout = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        txt_exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        txt_laptop = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        txt_mobile = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/logout-icon-32.png"))); // NOI18N
        btn_logout.setText("Đăng xuất");
        btn_logout.setFocusable(false);
        btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_logout);
        jToolBar1.add(jSeparator3);

        btn_laptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Laptop-icon.png"))); // NOI18N
        btn_laptop.setText("   Laptop   ");
        btn_laptop.setFocusable(false);
        btn_laptop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_laptop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_laptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laptopActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_laptop);
        jToolBar1.add(jSeparator4);

        btn_mobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/mobile-2-icon.png"))); // NOI18N
        btn_mobile.setText("   Mobile   ");
        btn_mobile.setFocusable(false);
        btn_mobile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_mobile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mobileActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_mobile);
        jToolBar1.add(jSeparator5);

        btn_gioithieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Actions-help-about-icon-32.png"))); // NOI18N
        btn_gioithieu.setText("Giới thiệu");
        btn_gioithieu.setFocusable(false);
        btn_gioithieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_gioithieu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_gioithieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gioithieuActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_gioithieu);

        jMenu1.setText("Hệ thống");

        txt_logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_DOWN_MASK));
        txt_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/logout-icon-16.png"))); // NOI18N
        txt_logout.setText(" Đăng xuất");
        txt_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_logoutActionPerformed(evt);
            }
        });
        jMenu1.add(txt_logout);
        jMenu1.add(jSeparator2);

        txt_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        txt_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        txt_exit.setText(" Thoát");
        txt_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_exitActionPerformed(evt);
            }
        });
        jMenu1.add(txt_exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        txt_laptop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        txt_laptop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Laptop-icon (1).png"))); // NOI18N
        txt_laptop.setText("Laptop");
        txt_laptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_laptopActionPerformed(evt);
            }
        });
        jMenu2.add(txt_laptop);
        jMenu2.add(jSeparator1);

        txt_mobile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        txt_mobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/mobile-2-icon.png"))); // NOI18N
        txt_mobile.setText(" Mobile");
        txt_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mobileActionPerformed(evt);
            }
        });
        jMenu2.add(txt_mobile);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Giới thiệu");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Actions-help-about-icon-16.png"))); // NOI18N
        jMenuItem1.setText("Giới thiệu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
            .addComponent(tpl_mainBoard)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpl_mainBoard, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_txt_exitActionPerformed

    private void txt_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mobileActionPerformed
         if(mMobile == null){
        mMobile = new QuanLyMobile();
        ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/quanlybanhangonl/icons/mobile-2-icon.png"));
        tpl_mainBoard.addTab("Quản lý Mobile", icon, mMobile, "Quản lý Mobile");
       }
        tpl_mainBoard.setSelectedComponent(mMobile);
    }//GEN-LAST:event_txt_mobileActionPerformed

    private void txt_laptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_laptopActionPerformed
        
       if(mlaptop == null){
        mlaptop = new QuanLyLaptop();
        ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/quanlybanhangonl/icons/Laptop-icon (1).png"));
        tpl_mainBoard.addTab("Quản lý Laptop", icon, mlaptop, "Quản lý Laptop");
       }
        tpl_mainBoard.setSelectedComponent(mlaptop);
        
        
    }//GEN-LAST:event_txt_laptopActionPerformed

    private void btn_laptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laptopActionPerformed
       if(mlaptop == null){
        mlaptop = new QuanLyLaptop();
        ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/quanlybanhangonl/icons/Laptop-icon (1).png"));
        tpl_mainBoard.addTab("Quản lý Laptop", icon, mlaptop, "Quản lý Laptop");
       }
        tpl_mainBoard.setSelectedComponent(mlaptop);
    }//GEN-LAST:event_btn_laptopActionPerformed

    private void btn_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mobileActionPerformed
          if(mMobile == null){
        mMobile = new QuanLyMobile();
        ImageIcon icon = new ImageIcon(getClass()
                .getResource("/com/mycompany/quanlybanhangonl/icons/mobile-2-icon.png"));
        tpl_mainBoard.addTab("Quản lý Mobile", icon, mMobile, "Quản lý Mobile");
       }
        tpl_mainBoard.setSelectedComponent(mMobile);
    }//GEN-LAST:event_btn_mobileActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GioiThieu gthieu = new GioiThieu(this,true);
        gthieu.setVisible(true);
             
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_gioithieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gioithieuActionPerformed
        GioiThieu gthieu = new GioiThieu(this,true);
        gthieu.setVisible(true);
    }//GEN-LAST:event_btn_gioithieuActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        LoginDialog loginDialog = new LoginDialog(this,true);
        
        loginDialog.setVisible(true);
        
        
        
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void txt_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_logoutActionPerformed
         LoginDialog loginDialog = new LoginDialog(this,true);
        
        loginDialog.setVisible(true);
        
        
        
    }//GEN-LAST:event_txt_logoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_gioithieu;
    private javax.swing.JButton btn_laptop;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_mobile;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTabbedPane tpl_mainBoard;
    private javax.swing.JMenuItem txt_exit;
    private javax.swing.JMenuItem txt_laptop;
    private javax.swing.JMenuItem txt_logout;
    private javax.swing.JMenuItem txt_mobile;
    // End of variables declaration//GEN-END:variables
}
