/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.quanlybanhangonl.ui;

import com.mycompany.quanlybanhangonl.dao.LapTopDao;
import com.mycompany.quanlybanhangonl.dao.MobileDao;
import com.mycompany.quanlybanhangonl.helpers.DataValidator;
import com.mycompany.quanlybanhangonl.helpers.ImageHelper;
import com.mycompany.quanlybanhangonl.helpers.MessageDialogHelper;
import com.mycompany.quanlybanhangonl.model.LapTop;
import com.mycompany.quanlybanhangonl.model.Mobile;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

public class QuanLyMobile extends javax.swing.JPanel {
  
    private MainForm parentForm;
     private DefaultTableModel tblModel;
     private byte[] personalImage;
    /**
     * Creates new form QuanLyMobile
     */
    public QuanLyMobile() {
        initComponents();
        initTable();
        loadDataToTable();
    }

    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã sản phẩm","Tên sản phẩm","Hãng","RAM","Số lượng","Giá Gốc","Tình trạng","Giá bán"});
        table_SPM.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try{
            MobileDao dao = new MobileDao();
            List<Mobile> list = dao.findAll();
            tblModel.setRowCount(0);
            for(Mobile it: list){
                tblModel.addRow(new Object[]{
                    it.getMaSP(), it.getTenSP(), it.getHang(), it.getRAM(), it.getSoLuong(), it.getGiaGoc(),
                    it.getTinhTrang()==1? "Máy mới":"Máy cũ", (it.getGiaGoc()+(it.getGiaGoc()/5))
                });
                
            }
            tblModel.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_MaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Hang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_RAM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_GiaGoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_Cu = new javax.swing.JCheckBox();
        btn_Moi = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        lbl_Image = new javax.swing.JLabel();
        btn_Anh = new javax.swing.JButton();
        btn_New = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txt_Search = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txt_GiaBan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_SPM = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản lý sản phẩm: Mobile");

        jLabel2.setText("Mã sản phẩm");

        jLabel3.setText(" Tên sản phẩm");

        txt_TenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenSPActionPerformed(evt);
            }
        });

        jLabel4.setText("Hãng");

        jLabel5.setText("RAM");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Giá gốc");

        txt_GiaGoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_GiaGocFocusLost(evt);
            }
        });
        txt_GiaGoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_GiaGocActionPerformed(evt);
            }
        });

        jLabel8.setText("Tình trạng");

        btn_Cu.setText("Máy cũ");

        btn_Moi.setText("Máy mới");

        lbl_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-48.png"))); // NOI18N

        btn_Anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-16.png"))); // NOI18N
        btn_Anh.setText("Thêm ảnh");
        btn_Anh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_Anh)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Anh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/new-icon-16.png"))); // NOI18N
        btn_New.setText("Tạo mới");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Save-icon.png"))); // NOI18N
        btn_Save.setText("Lưu");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_Update.setText("Cập nhật");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btn_Delete.setText("Xóa");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        jLabel10.setText(" Nhập mã cần tìm");

        txt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SearchActionPerformed(evt);
            }
        });

        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/search-icon-16.png"))); // NOI18N
        btn_Search.setText("Tìm kiếm");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Giá bán ");

        txt_GiaBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_GiaBan.setText("0");

        table_SPM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_SPM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_SPMMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_SPM);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8))
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_MaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(txt_TenSP)
                                            .addComponent(txt_Hang)
                                            .addComponent(txt_RAM)
                                            .addComponent(txt_SoLuong)
                                            .addComponent(txt_GiaGoc)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btn_Cu)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btn_Moi)))
                                        .addGap(24, 24, 24)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(169, 169, 169)
                                                .addComponent(txt_GiaBan))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(128, 128, 128)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(223, 223, 223))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_RAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_GiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btn_Cu)
                            .addComponent(btn_Moi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Search))
                        .addGap(72, 72, 72)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txt_GiaBan)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_New)
                    .addComponent(btn_Save)
                    .addComponent(btn_Update)
                    .addComponent(btn_Delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SearchActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        //nút UPDATE
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmpty(txt_MaSP,sb,"Mã sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_TenSP,sb,"Tên sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_Hang,sb,"Hãng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_SoLuong,sb,"Số lượng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_GiaGoc,sb,"Giá gốc sản phẩm không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn cập nhật sản phẩm không?",
                "Hỏi")== JOptionPane.NO_OPTION){
            return;
        }

        try{
            Mobile mb = new Mobile();
            mb.setMaSP(txt_MaSP.getText());
            mb.setTenSP(txt_TenSP.getText());
            mb.setHang(txt_Hang.getText());
            mb.setRAM(txt_RAM.getText());
            mb.setGiaGoc(Float.parseFloat(txt_GiaGoc.getText()));
            mb.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
            mb.setMaSP(txt_MaSP.getText());
            mb.setTinhTrang(btn_Moi.isSelected()?1: 0);
            mb.setAnh(personalImage);
            
            MobileDao dao = new MobileDao();
            if(dao.update(mb)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin đã được cập nhật", "Thông báo");
                loadDataToTable();
            }else{
              MessageDialogHelper.showMessageDialog(parentForm, "Thông tin chưa được cập nhật do lỗi!", "Thông báo");
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");
                    
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        //nút SAVED
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmpty(txt_MaSP,sb,"Mã sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_TenSP,sb,"Tên sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_Hang,sb,"Hãng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_SoLuong,sb,"Số lượng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_GiaGoc,sb,"Giá gốc sản phẩm không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try{
            Mobile mb = new Mobile();
            mb.setMaSP(txt_MaSP.getText());
            mb.setTenSP(txt_TenSP.getText());
            mb.setHang(txt_Hang.getText());
            mb.setRAM(txt_RAM.getText());
            mb.setGiaGoc(Float.parseFloat(txt_GiaGoc.getText()));
            mb.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
            mb.setMaSP(txt_MaSP.getText());
            mb.setTinhTrang(btn_Moi.isSelected()?1: 0);
            mb.setAnh(personalImage);
            
            MobileDao dao = new MobileDao();
            if(dao.insert(mb)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin đã được lưu", "Thông báo");
                loadDataToTable();
            }else{
              MessageDialogHelper.showMessageDialog(parentForm, "Thông tin không được lưu do lỗi!", "Thông báo");
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,
                    e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void txt_TenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenSPActionPerformed

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        //nút NEW
        txt_MaSP.setText("");
        txt_TenSP.setText("");
        txt_Hang.setText("");
        txt_SoLuong.setText("");
        txt_GiaGoc.setText("");
        txt_RAM.setText("");
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-48.png"));
        lbl_Image.setIcon(icon);                   
    }//GEN-LAST:event_btn_NewActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // nút DELETE
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmpty(txt_MaSP,sb,"Mã sản phẩm không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa sản phẩm không?",
                "Hỏi")== JOptionPane.NO_OPTION){
            return;
        }

        try{
            Mobile mb = new Mobile();
            mb.setMaSP(txt_MaSP.getText());
            MobileDao dao = new MobileDao();
            if(dao.delete(mb)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin đã được xóa", "Thông báo");
                loadDataToTable();
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin chưa được xóa do lỗi!", "Thông báo");
                btnNewActionPerformed(evt);
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,
                    e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void txt_GiaGocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_GiaGocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_GiaGocActionPerformed

    private void txt_GiaGocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_GiaGocFocusLost
        float gia = Float.parseFloat(txt_GiaGoc.getText());
        
        float kq = gia + (gia/5);
        String st = String.format("%.2f", kq);
        txt_GiaBan.setText(st);
    }//GEN-LAST:event_txt_GiaGocFocusLost

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        try{
            MobileDao dao = new MobileDao();
            Mobile mb = dao.findByID(txt_Search.getText());
            
            if(mb != null){
                     txt_MaSP.setText(mb.getMaSP());
                     txt_TenSP.setText(mb.getTenSP());
                     txt_Hang.setText(mb.getHang());
                     txt_RAM.setText(mb.getRAM());
                     txt_SoLuong.setText(String.format("%d", mb.getSoLuong()) );
                     txt_GiaGoc.setText(String.format("%.1f", mb.getGiaGoc()));
                     btn_Moi.setSelected(mb.getTinhTrang()==1?true:false);
                     Image img = ImageHelper.createImageFromByteArray(mb.getAnh(), "jpg");
                     lbl_Image.setIcon(new ImageIcon(img));
                     personalImage = mb.getAnh();
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Không tìm thấy mã sản phẩm", "Thông báo");
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
        
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_AnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnhActionPerformed
        JFileChooser chooser = new  JFileChooser();
        chooser.setFileFilter(new FileFilter(){
                   
            @Override
            public boolean accept(File f){
                if(f.isDirectory()){
                    return true;
                }else{
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }
            
            @Override
            public String getDescription(){
                return "Image File (*.jpg)";
            }
        });
        
        if(chooser.showOpenDialog(parentForm)== JFileChooser.CANCEL_OPTION){
            return;
        }
        
        File file = chooser.getSelectedFile();
        try{
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageHelper.resize(icon.getImage(), 140, 160);
            ImageIcon resizeIcon = new ImageIcon(img);
            lbl_Image.setIcon(resizeIcon);
            personalImage = ImageHelper.toByteArray(img, "jpg");
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
        
        
    }//GEN-LAST:event_btn_AnhActionPerformed

    private void table_SPMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_SPMMouseClicked
        try{
             int row = table_SPM.getSelectedRow();
             if(row >= 0){
                 String id = (String) table_SPM.getValueAt(row, 0);
                 MobileDao dao = new MobileDao();
                 Mobile mb = dao.findByID(id);
                 
                 if(mb != null){
                     txt_MaSP.setText(mb.getMaSP());
                     txt_TenSP.setText(mb.getTenSP());
                     txt_Hang.setText(mb.getHang());
                     txt_RAM.setText(mb.getRAM());
                     txt_SoLuong.setText(String.format("%d", mb.getSoLuong()) );
                     txt_GiaGoc.setText(String.format("%.1f", mb.getGiaGoc()));
                     btn_Moi.setSelected(mb.getTinhTrang()==1?true:false);
                     if(mb.getAnh ()!= null){
                         Image img = ImageHelper.createImageFromByteArray(mb.getAnh(), "jpg");
                         lbl_Image.setIcon(new ImageIcon(img));
                         personalImage = mb.getAnh();
                     }else{
                         personalImage = mb.getAnh();
                         ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-48.png"));
                         lbl_Image.setIcon(icon);
                     }
                 }
             }
         }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
         }
        
        
        
    }//GEN-LAST:event_table_SPMMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anh;
    private javax.swing.JCheckBox btn_Cu;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JCheckBox btn_Moi;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_Image;
    private javax.swing.JTable table_SPM;
    private javax.swing.JLabel txt_GiaBan;
    private javax.swing.JTextField txt_GiaGoc;
    private javax.swing.JTextField txt_Hang;
    private javax.swing.JTextField txt_MaSP;
    private javax.swing.JTextField txt_RAM;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_TenSP;
    // End of variables declaration//GEN-END:variables
  private void btnNewActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
