/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//Tuan an shit
package com.mycompany.quanlybanhangonl.ui;

import com.mycompany.quanlybanhangonl.dao.LapTopDao;
import com.mycompany.quanlybanhangonl.helpers.DataValidator;
import com.mycompany.quanlybanhangonl.helpers.ImageHelper;
import com.mycompany.quanlybanhangonl.helpers.MessageDialogHelper;
import com.mycompany.quanlybanhangonl.model.LapTop;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lennovo
 */
public class QuanLyLaptop extends javax.swing.JPanel {
     private MainForm parentForm;
     private DefaultTableModel tblModel;
     private byte[] personalImage;
    /**
     * Creates new form QuanLyLaptop
     */
    public QuanLyLaptop() {
        initComponents();
        
        initTable();
        loadDataToTable();
    }

    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã sản phẩm","Tên sản phẩm","Hãng","CPU","Số lượng","Giá Gốc","Tình trạng","Giá bán"});
        table_SP.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try{
            LapTopDao dao = new LapTopDao();
            List<LapTop> list = dao.findAll();
            tblModel.setRowCount(0);
            for(LapTop it: list){
                tblModel.addRow(new Object[]{
                    it.getMaSP(), it.getTenSP(), it.getHang(), it.getCPU(), it.getSoLuong(), it.getGiaGoc(),
                    it.getTinhTrang()==1? "Máy mới":"Máy cũ", (it.getGiaGoc()+(it.getGiaGoc()/5))
                });
                
            }
            tblModel.fireTableDataChanged();
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");        
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_MaSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_TenSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Hang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_CPU = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_SoLuong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_GiaGoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_Cu = new javax.swing.JCheckBox();
        btn_Moi = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        lbl_Image = new javax.swing.JLabel();
        btn_Anh = new javax.swing.JButton();
        btn_New = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_SP = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txt_Search = new javax.swing.JTextField();
        btn_Search = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txt_GiaBan = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Quản lý sản phẩm: LapTop");

        jLabel2.setText("Mã sản phẩm");

        jLabel3.setText(" Tên sản phẩm");

        txt_TenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenSPActionPerformed(evt);
            }
        });

        jLabel4.setText("Hãng");

        jLabel5.setText("RAM");

        jLabel6.setText("Số lượng");

        jLabel7.setText("Giá gốc");

        txt_GiaGoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_GiaGocFocusLost(evt);
            }
        });

        jLabel8.setText("Tình trạng");

        buttonGroup1.add(btn_Cu);
        btn_Cu.setText("Máy cũ");

        buttonGroup1.add(btn_Moi);
        btn_Moi.setText("Máy mới");

        lbl_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-48.png"))); // NOI18N

        btn_Anh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-16.png"))); // NOI18N
        btn_Anh.setText("Thêm ảnh");
        btn_Anh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AnhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_Anh)
                        .addContainerGap(31, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Anh)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/new-icon-16.png"))); // NOI18N
        btn_New.setText("Tạo mới");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Save-icon.png"))); // NOI18N
        btn_Save.setText("Lưu");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btn_Update.setText("Cập nhật");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/Actions-edit-delete-icon-16.png"))); // NOI18N
        btn_Delete.setText("Xóa");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        table_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_SP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_SPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_SP);

        jLabel10.setText(" Nhập mã cần tìm");

        txt_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SearchActionPerformed(evt);
            }
        });

        btn_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/search-icon-16.png"))); // NOI18N
        btn_Search.setText("Tìm kiếm");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Giá bán ");

        txt_GiaBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_GiaBan.setText(" 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_MaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txt_TenSP)
                    .addComponent(txt_Hang)
                    .addComponent(txt_CPU)
                    .addComponent(txt_SoLuong)
                    .addComponent(txt_GiaGoc)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Cu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Moi)))
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(txt_GiaBan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(727, 727, 727))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_TenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Hang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(txt_GiaGoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btn_Cu)
                            .addComponent(btn_Moi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_New)
                            .addComponent(btn_Save)
                            .addComponent(btn_Update)
                            .addComponent(btn_Delete))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Search))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(25, 25, 25)
                        .addComponent(txt_GiaBan)))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(565, 565, 565))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenSPActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        //Nút saved
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmpty(txt_MaSP,sb,"Mã sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_TenSP,sb,"Tên sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_Hang,sb,"Hãng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_SoLuong,sb,"Số lượng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_GiaGoc,sb,"Giá gốc sản phẩm không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try{
            LapTop lt = new LapTop();
            lt.setMaSP(txt_MaSP.getText());
            lt.setTenSP(txt_TenSP.getText());
            lt.setHang(txt_Hang.getText());
            lt.setCPU(txt_CPU.getText());
            lt.setGiaGoc(Float.parseFloat(txt_GiaGoc.getText()));
            lt.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
            lt.setMaSP(txt_MaSP.getText());
            lt.setTinhTrang(btn_Moi.isSelected()?1: 0);
            lt.setAnh(personalImage);
            
            LapTopDao dao = new LapTopDao();
            if(dao.insert(lt)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin đã được lưu", "Thông báo");
                loadDataToTable();
            }else{
              MessageDialogHelper.showMessageDialog(parentForm, "Thông tin không được lưu do lỗi!", "Thông báo");
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,
                    e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        //nút Update
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmpty(txt_MaSP,sb,"Mã sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_TenSP,sb,"Tên sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_Hang,sb,"Hãng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_SoLuong,sb,"Số lượng sản phẩm không được để trống");
        DataValidator.ValidateEmpty(txt_GiaGoc,sb,"Giá gốc sản phẩm không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn cập nhật sản phẩm không?",
                "Hỏi")== JOptionPane.NO_OPTION){
            return;
        }

        try{
            LapTop lt = new LapTop();
            lt.setMaSP(txt_MaSP.getText());
            lt.setTenSP(txt_TenSP.getText());
            lt.setHang(txt_Hang.getText());
            lt.setCPU(txt_CPU.getText());
            lt.setGiaGoc(Float.parseFloat(txt_GiaGoc.getText()));
            lt.setSoLuong(Integer.parseInt(txt_SoLuong.getText()));
            lt.setMaSP(txt_MaSP.getText());
            lt.setTinhTrang(btn_Moi.isSelected()?1: 0);
            lt.setAnh(personalImage);
            
            LapTopDao dao = new LapTopDao();
            if(dao.update(lt)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin đã được cập nhật", "Thông báo");
                loadDataToTable();
            }else{
              MessageDialogHelper.showMessageDialog(parentForm, "Thông tin chưa được cập nhật do lỗi!", "Thông báo");
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,e.getMessage(), "Lỗi");
                    
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void txt_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SearchActionPerformed

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        //Nút New
        txt_MaSP.setText("");
        txt_TenSP.setText("");
        txt_Hang.setText("");
        txt_SoLuong.setText("");
        txt_GiaGoc.setText("");
        txt_CPU.setText("");
        personalImage = null;
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-48.png"));
        lbl_Image.setIcon(icon);
    }//GEN-LAST:event_btn_NewActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        //Nút DELETE
        StringBuilder sb = new StringBuilder();
        DataValidator.ValidateEmpty(txt_MaSP,sb,"Mã sản phẩm không được để trống");
        if(sb.length()>0){
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if(MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xóa sản phẩm không?",
                "Hỏi")== JOptionPane.NO_OPTION){
            return;
        }

        try{
            LapTop lt = new LapTop();
            lt.setMaSP(txt_MaSP.getText());
            LapTopDao dao = new LapTopDao();
            if(dao.delete(lt)){
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin đã được xóa", "Thông báo");
                loadDataToTable();
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Thông tin chưa được xóa do lỗi!", "Thông báo");
                btnNewActionPerformed(evt);
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm,
                    e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void table_SPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_SPMouseClicked
         try{
             int row = table_SP.getSelectedRow();
             if(row >= 0){
                 String id = (String) table_SP.getValueAt(row, 0);
                 LapTopDao dao = new LapTopDao();
                 LapTop lt = dao.findByID(id);
                 
                 if(lt != null){
                     txt_MaSP.setText(lt.getMaSP());
                     txt_TenSP.setText(lt.getTenSP());
                     txt_Hang.setText(lt.getHang());
                     txt_CPU.setText(lt.getCPU());
                     txt_SoLuong.setText(String.format("%d", lt.getSoLuong()) );
                     txt_GiaGoc.setText(String.format("%.1f", lt.getGiaGoc()));
                     btn_Moi.setSelected(lt.getTinhTrang()==1?true:false);
                     if(lt.getAnh ()!= null){
                         Image img = ImageHelper.createImageFromByteArray(lt.getAnh(), "jpg");
                         lbl_Image.setIcon(new ImageIcon(img));
                         personalImage = lt.getAnh();
                     }else{
                         personalImage = lt.getAnh();
                         ImageIcon icon = new ImageIcon(getClass().getResource("/com/mycompany/quanlybanhangonl/icons/open-file-icon-48.png"));
                         lbl_Image.setIcon(icon);
                     }
                 }
             }
         }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
         }
        
        
    }//GEN-LAST:event_table_SPMouseClicked

    private void txt_GiaGocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_GiaGocFocusLost
        float gia = Float.parseFloat(txt_GiaGoc.getText());
        
        float kq = gia + (gia/5);
        String st = String.format("%.2f", kq);
        txt_GiaBan.setText(st);
    }//GEN-LAST:event_txt_GiaGocFocusLost

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
        //Tìm kiếm
        try{
            LapTopDao dao = new LapTopDao();
            LapTop lt = dao.findByID(txt_Search.getText());
            
            if(lt != null){
                     txt_MaSP.setText(lt.getMaSP());
                     txt_TenSP.setText(lt.getTenSP());
                     txt_Hang.setText(lt.getHang());
                     txt_CPU.setText(lt.getCPU());
                     txt_SoLuong.setText(String.format("%d", lt.getSoLuong()) );
                     txt_GiaGoc.setText(String.format("%.1f", lt.getGiaGoc()));
                     btn_Moi.setSelected(lt.getTinhTrang()==1?true:false);
                     Image img = ImageHelper.createImageFromByteArray(lt.getAnh(), "jpg");
                     lbl_Image.setIcon(new ImageIcon(img));
                     personalImage = lt.getAnh();
            }else{
                MessageDialogHelper.showMessageDialog(parentForm, "Không tìm thấy mã sản phẩm", "Thông báo");
            }
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_AnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AnhActionPerformed
        JFileChooser chooser = new  JFileChooser();
        chooser.setFileFilter(new FileFilter(){
                   
            @Override
            public boolean accept(File f){
                if(f.isDirectory()){
                    return true;
                }else{
                    return f.getName().toLowerCase().endsWith(".jpg");
                }
            }
            
            @Override
            public String getDescription(){
                return "Image File (*.jpg)";
            }
        });
        
        if(chooser.showOpenDialog(parentForm)== JFileChooser.CANCEL_OPTION){
            return;
        }
        
        File file = chooser.getSelectedFile();
        try{
            ImageIcon icon = new ImageIcon(file.getPath());
            Image img = ImageHelper.resize(icon.getImage(), 140, 160);
            ImageIcon resizeIcon = new ImageIcon(img);
            lbl_Image.setIcon(resizeIcon);
            personalImage = ImageHelper.toByteArray(img, "jpg");
        }catch(Exception e){
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
        
    }//GEN-LAST:event_btn_AnhActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Anh;
    private javax.swing.JCheckBox btn_Cu;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JCheckBox btn_Moi;
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbl_Image;
    private javax.swing.JTable table_SP;
    private javax.swing.JTextField txt_CPU;
    private javax.swing.JLabel txt_GiaBan;
    private javax.swing.JTextField txt_GiaGoc;
    private javax.swing.JTextField txt_Hang;
    private javax.swing.JTextField txt_MaSP;
    private javax.swing.JTextField txt_Search;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_TenSP;
    // End of variables declaration//GEN-END:variables

    private void btnNewActionPerformed(ActionEvent evt) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
